context:
  version: "0.7.21"

package:
  name: python-hyperscan
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/h/hyperscan/hyperscan-${{ version }}.tar.gz
    sha256: 40248994e8da523da612d18445fefa9f159de59209ea9a530f35a2abcaa28f8d

build:
  number: 0
  skip: win
  script: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - pkg-config
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
  host:
    - python
    - pip
    - scikit-build-core
    - vectorscan
  run:
    - python

tests:
  - python:
      imports:
        - hyperscan
      pip_check: true

about:
  summary: Python bindings for Hyperscan.
  description: |
    A CPython extension for Vectorscan, an open source fork of Hyperscan,
    Intel's open source (prior to version 5.4), high-performance multiple
    regex matching library.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/darvid/python-hyperscan
  documentation: https://python-hyperscan.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - chrisburr
    - synapticarbors
