context:
  version: 0.7.8

package:
  name: python-hyperscan
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/h/hyperscan/hyperscan-${{ version }}.tar.gz
    sha256: 1ed6c87eaf32f77c89fec8c102f20bc677e44c4ce80bde903620f274ea4b8ed7

build:
  number: 1
  skip: win
  script: ${{ PYTHON }} -m pip install .

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - pkg-config
  host:
    - python
    - pip
    - setuptools
    - pdm-backend
    - vectorscan
  run:
    - python

tests:
  - python:
      imports:
        - hyperscan
      pip_check: true

about:
  summary: Python bindings for Hyperscan.
  description: |
    A CPython extension for Vectorscan, an open source fork of Hyperscan,
    Intel's open source (prior to version 5.4), high-performance multiple
    regex matching library.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/darvid/python-hyperscan
  documentation: https://python-hyperscan.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - chrisburr
